name: CI
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: akondas/smarttesting:php-8.2.11
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: Install main composer
        run: composer install

      - name: Install modules
        run: composer install-modules

      - name: Run tests
        run: composer tests
